{% set name = "ansi2html" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38b82a298482a1fa2613f0f9c9beb3db72a8f832eeac58eb2e47bf32cd37f6d5
  patches:
    - 0001-No-python3.exe-on-Windows.patch

build:
  number: 2
  skip: true  # [py<36]
  entry_points:
    - ansi2html=ansi2html.converter:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six
    - importlib-metadata  # [py<38]

test:
  source_files:
    - tests
  imports:
    - ansi2html
  commands:
    - pytest tests/test_ansi2html.py
    - ansi2html --help
  requires:
    - pytest

about:
  home: https://pypi.python.org/pypi/ansi2html
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Convert text with ANSI color codes to HTML or to LaTeX.
  description: |
    ansi2html allows users to convert text with ANSI color codes
    to HTML or to Latex.
  doc_url: https://pypi.python.org/pypi/ansi2html/
  doc_source_url: https://github.com/pycontribs/ansi2html/blob/master/README.rst
  dev_url: https://github.com/pycontribs/ansi2html

extra:
  recipe-maintainers:
    - nehaljwani
