build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
travis:
  secure:
    BINSTAR_TOKEN: ehU9MyEOnV27LOi5rmzU1U2PjcWlo0w6FZSQCjMrDg/kdg+L6xhBULzf86UT8K2EFWRl5Y2c8Cv4ocx+7aHcLkv50vY9wVS2yh/KbFQhPZP25fPA+veuVtLZ5ziLvloA7PvqLNI5wUcNi1MSJ3D6EsyCVgxifaQ6VLsmYubPdeDuUevobVIIl0Zmr7W5vmvo4CAyAgtOg0136kDIrJ5dFP/IXiQqte6K6LVuGS5fKAFsu/czf5dAhrsZpJQpcyg72LCaMCim1LFK3CagSivwPCIWSjMw2T76yKkOaM8HSj7ebRphCS9YfeZKF48nFkmFYe/xsPkCwWBQt54Fnj+yrW1hiobTVAgGD8aTRCMrvG4Q7WXs5HXPSOFveA7hULJykccoPA/9AAZixKX+EUudMOP+Kfi+N/5xby27vKZPObg+9jmv/wpblsQXvBMf5C0Bzhwu1p8+OZ96ZmkbZUII/iazS+GXPSWIXLS/BYgIKOKlsfiLrW/7bxXzJgTM3kbMYM5k1TLI76UM2CDF/IshGIA9TuBWbDckrB7bimb9CRMG1D8+DR3Y8DYbJ+l46Svs0NDR9I6s7WAFSSfeeqFNguynSm0GHY4UjqgnfSWRV3HhFpGxCCMoJHrZMKmnd0G2a93I/LG6n20hilAHUpOq1UdBs4fLopG76/gyfXErIUg=
